site_name: Full Stack Deep Learning
site_url: https://fullstackaischool.com
repo_url: https://github.com/full-stack-deep-learning/full-stack-deep-learning.github.io
repo_name: GitHub

site_description: Our mission is to help you go from a promising ML experiment to a shipped product, with real-world impact.
site_author: Full Stack Deep Learning
copyright: Full Stack Deep Learning, LLC. 2021
google_analytics: ['UA-118687450-1', 'fullstackaischool.com']

theme:
  name: material
  custom_dir: overrides
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/full_stack_dl
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCVchfoB65aVtQiDITbGq2LQ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/full-stack-deep-learning/posts/

nav:
  - 'Home': 'index.md'
  - 'Spring 2021':
    - 'Schedule': 'spring2021/index.md'
    - 'Lectures':
      - 'spring2021/lecture-1.md'
    - 'Labs':
      - 'spring2021/lab-1.md'
    - 'Synchronous Online Course': 'spring2021/synchronous.md'
  - 'Fall 2019': 'https://fall2019.fullstackdeeplearning.com'
