repo_url: https://github.com/full-stack-deep-learning/fsdl-text-recognizer-project
repo_name: GitHub

site_name: Full Stack Deep Learning
site_url: https://fullstackdeeplearning.com
site_description: The community for people building ML-powered products.
site_author: Full Stack Deep Learning
site_image: https://fullstackdeeplearning.com/images/pancakes.png
site_image_alt: Image explaining what FSDL covers.

copyright: Full Stack Deep Learning, LLC. 2022

google_analytics:
  - UA-118687450-1
  - auto
theme:
  custom_dir: overrides
  favicon: images/favicon.png
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
  font: false
  logo: images/favicon.png
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/git-alt
extra_css:
  - stylesheets/extra.css
edit_uri: ""

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.superfences

plugins:
  - search
  - macros

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/full_stack_dl
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/FullStackDeepLearning
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/full-stack-deep-learning/posts/

nav:
  - 'Home': 'index.md'
  - 'Course':
    - 'FSDL 2022':
      - 'Main': 'course/2022/index.md'
      - 'Labs': 'course/2022/labs.md'
      - 'Lecture 1: Introduction': 'course/2022/lecture-1-introduction.md'
      # - 'Lecture 2: Development Infrastructure': 'course/2022/lecture-2-development-infrastructure.md'
      # - 'Lecture 3: Troubleshooting & Testing': 'course/2022/lecture-3-troubleshooting-and-testing.md'
      # - 'Lecture 4: Data Management': 'course/2022/lecture-4-data-management.md'
      # - 'Lecture 5: Deployment': 'course/2022/lecture-5-deployment.md'
      # - 'Lecture 6: Continual Learning': 'course/2022/lecture-6-continual-learning.md'
      # - 'Lecture 7: Foundation Models': 'course/2022/lecture-7-foundation-models.md'
      # - 'Lecture 8: Project Management': 'course/2022/lecture-8-project-management.md'
      # - 'Lecture 9: Ethics': 'course/2022/lecture-9-ethics.md'
      - 'Course Description': 'course/2022/description.md' 
    - 'FSDL 2021':
      - 'Overview': 'spring2021/index.md'
      - 'Projects': 'spring2021/projects.md'
      - 'Lectures':
        - 'spring2021/lecture-1.md'
        - 'spring2021/notebook-1.md'
        - 'spring2021/lecture-2a.md'
        - 'spring2021/lecture-2b.md'
        - 'spring2021/lecture-3.md'
        - 'spring2021/lecture-4.md'
        - 'spring2021/lecture-5.md'
        - 'spring2021/lecture-6.md'
        - 'spring2021/lecture-7.md'
        - 'spring2021/lecture-8.md'
        - 'spring2021/lecture-9.md'
        - 'spring2021/lecture-10.md'
        - 'spring2021/lecture-11.md'
        - 'spring2021/lecture-12.md'
        - 'spring2021/lecture-13.md'
        - 'spring2021/panel.md'
      - 'Labs':
        - 'spring2021/lab-1.md'
        - 'spring2021/lab-2.md'
        - 'spring2021/lab-3.md'
        - 'spring2021/lab-4.md'
        - 'spring2021/lab-5.md'
        - 'spring2021/lab-6.md'
        - 'spring2021/lab-7.md'
        - 'spring2021/lab-8.md'
        - 'spring2021/lab-9.md'
      - 'Synchronous Online Course': 'spring2021/synchronous.md'
    - 'Older':
      - 'FSDL 2021 (Berkeley)': https://bit.ly/berkeleyfsdl
      - 'FSDL 2020 (UW)': https://bit.ly/uwfsdl
      - 'FSDL 2019 (Online)': https://fall2019.fullstackdeeplearning.com
      - 'FSDL 2019 (Bootcamp)': '/march2019.html'
      - 'FSDL 2018 (Bootcamp)': '/august2018.html'
  # - 'Summit': 'summit.md'

watch:
- docs
- assets
- mkdocs.yml
- overrides
