site_name: Full Stack Deep Learning
site_url: https://fullstackdeeplearning.com
repo_url: https://github.com/full-stack-deep-learning/website
repo_name: GitHub

site_description: Our mission is to help you go from a promising ML experiment to a shipped product, with real-world impact.
site_author: Full Stack Deep Learning
copyright: Full Stack Deep Learning, LLC. 2021
google_analytics:
  - UA-118687450-1
  - auto

theme:
  name: material
  custom_dir: overrides
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/full_stack_dl
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/FullStackDeepLearning
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/full-stack-deep-learning/posts/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/fullstackdl/

nav:
  - 'Home': 'index.md'
  - 'Spring 2021':
    - 'Spring 2021 Schedule': 'spring2021/index.md'
    - 'Lectures':
      - 'spring2021/lecture-1.md'
      - 'spring2021/notebook-1.md'
      - 'spring2021/lecture-2a.md'
      - 'spring2021/lecture-2b.md'
      - 'spring2021/lecture-3.md'
      - 'spring2021/lecture-4.md'
      - 'spring2021/lecture-5.md'
      - 'spring2021/lecture-6.md'
      - 'spring2021/lecture-7.md'
      - 'spring2021/lecture-8.md'
      - 'spring2021/lecture-9.md'
      - 'spring2021/lecture-10.md'
      - 'spring2021/lecture-11.md'
      - 'spring2021/lecture-12.md'
      # - 'spring2021/lecture-13.md' # April 26
    - 'Labs':
      - 'spring2021/lab-1.md'
      - 'spring2021/lab-2.md'
      - 'spring2021/lab-3.md'
      - 'spring2021/lab-4.md'
      - 'spring2021/lab-5.md'
      - 'spring2021/lab-6.md'
      - 'spring2021/lab-7.md'
      - 'spring2021/lab-8.md'
      - 'spring2021/lab-9.md'
      # - 'spring2021/lab-10.md'
    - 'Synchronous Online Course': 'spring2021/synchronous.md'
  - 'Fall 2019': 'https://fall2019.fullstackdeeplearning.com'
